### ISSUE TITLE
features to enable

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/cp2k-feedstock#19]
from [installation instructions](https://github.com/cp2k/cp2k/blob/master/INSTALL.md)

- [ ] MPI / scalapack - (Linux: done https://github.com/conda-forge/cp2k-feedstock/pull/21, OSX: open, see https://github.com/conda-forge/cp2k-feedstock/issues/22)
- [ ] libint see https://github.com/conda-forge/cp2k-feedstock/pull/12#issuecomment-759487406
- [ ] CUDA support (see [thread](https://github.com/conda-forge/conda-forge.github.io/issues/63)  and [example](https://github.com/conda-forge/nvidia-apex-feedstock/blob/master/recipe/meta.yaml) )
- [x] libxc - PR https://github.com/conda-forge/cp2k-feedstock/pull/14
- [ ] elpa (perhaps hold off, see https://github.com/cp2k/cp2k/issues/1444 )
- [x] spglib
- [x] sirius - PR https://github.com/conda-forge/cp2k-feedstock/pull/34
- [ ] libvori

**Comment by ltalirz** [comment]
Hey @dev-zero, @annahehn reached out with regards to adding libint to the cp2k version built on conda-forge.

As you pointed out in https://github.com/conda-forge/cp2k-feedstock/pull/12#issuecomment-759487406 , cp2k needs a specially configured libint so I guess we can't use the one from the [libint feedstock](https://github.com/conda-forge/libint-feedstock) (?).

However, I guess it may be relatively straightforward to build this specific libint during the cp2k build process (?).
Could you perhaps provide the rough instructions we would need to add to the [build.sh](https://github.com/conda-forge/cp2k-feedstock/blob/main/recipe/build.sh) in order to do this?

P.S. I guess it would increase the build time significantly but looking at the libint feedstock their build takes of the order of 44 minutes so perhaps it's still doable.

**Comment by dev-zero** [comment]
> Hey @dev-zero, @annahehn reached out with regards to adding libint to the cp2k version built on conda-forge.
> 
> As you pointed out in [#12 (comment)](https://github.com/conda-forge/cp2k-feedstock/pull/12#issuecomment-759487406) , cp2k needs a specially configured libint so I guess we can't use the one from the [libint feedstock](https://github.com/conda-forge/libint-feedstock) (?).

No, you most likely can't unless it is configured exactly the same way as required (which is usually not the case).
Details on how we need libint to be built can be found here: https://github.com/cp2k/libint-cp2k/blob/master/Jenkinsfile

> However, I guess it may be relatively straightforward to build this specific libint during the cp2k build process (?). Could you perhaps provide the rough instructions we would need to add to the [build.sh](https://github.com/conda-forge/cp2k-feedstock/blob/main/recipe/build.sh) in order to do this?

Sure, I somewhat assumed that this is a no-go (as it is for many Linux distros).

What you need is the 2.6.0 tarball from https://github.com/cp2k/libint-cp2k/releases (or the CP2K package mirror) which contains the libint source code with the first step (the generation of the code with the required configuration) already done. From there you can do a simple configure/make/make install with the only thing to remember is to pass `--enable-fortran`. The toolchain script can serve as a blueprint (and a reminder to ensure CC/CFLAGS are set):
https://github.com/cp2k/cp2k/blob/4eb5f9a884a8e3083aa1322b1d05a82a7f2f3db8/tools/toolchain/scripts/stage3/install_libint.sh#L81-L94
This is not an MPI-parallel package, so "normal" compilers can be used.
If I'm not mistaken you should end up with a static library, modify the arch files accordingly (the easiest is to do a cp2k build locally with the toolchain to get a template, otherwise @annahehn can provide an example arch file.

> P.S. I guess it would increase the build time significantly but looking at the libint feedstock their build takes of the order of 44 minutes so perhaps it's still doable.

On fast machines it is doable, especially when using our pre-prepared tarball.

Wrt your list of dependencies: libxsmm (not libsmm) which is likely part of the conda would be very important for CP2K. The only requirement is that the Fortran bindings are enabled. libvori would also be a low-hanging fruit you could integrate in the same way as libint.

**Comment by dev-zero** [comment]
Expect the binary size to grow (+80M) as libint consists of a lot of templated unrolled code. If debug symbols `-g` are enabled within conda: disable it for libint to half the size (or call `strip` on `libint2.a` before linking it with cp2k).

**Comment by oschuett** [comment]
Maybe the build time and binary size could be reduced by [lowering `--with-opt-am`](https://github.com/cp2k/libint-cp2k/blob/e17c65f55083036a718ba6f95972ea70ef1588f4/Jenkinsfile#L64)?

**Comment by ltalirz** [comment]
Dear both, thanks a lot for the quick reply and for the thoughtful suggestions!

Just for reference, I haven't started adding libint since @annahehn mentioned a vistor in their group may have a stab at adding support here.

@dev-zero Concerning libsmm: I think in the list above I likely meant to write `libxsmm` rather than `libsmm`.
Is there even a way to turn off libsmm in cp2k?
`libxsmm` is on conda-forge and could be added.

**Comment by dev-zero** [comment]
@ltalirz libsmm is/was optional before and required extra steps. The default is to use blas instead.

**Comment by ltalirz** [comment]
I see. I just searched for "smm" in the [installation instructions](https://github.com/cp2k/cp2k/blob/master/INSTALL.md) and did not see any mention of a related configuration option. Am I overlooking something?

**Comment by oschuett** [comment]
I removed libsmm from the toolchain and the installation instructions (https://github.com/cp2k/cp2k/commit/9d664f589f2974eb2abbd05dbca882b4de6af279), see also https://github.com/cp2k/cp2k/issues/2044.

**Comment by ltalirz** [comment]
Thanks for the clarification - now that I look back into it, the feedstock already builds cp2k with libxsmm support. When I opened this issue, I probably only glanced over the installation instructions and failed to realize that libxsmm supersedes libsmm and that there is no point in adding both.

I've removed the corresponding bullet point from the to-do list.

**Comment by mkrack** [comment]
I am closing this issue, since the features listed above have been enabled in the meantime.
